# Generated by Django 3.0.1 on 2020-01-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0002_auto_20200101_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keytransfer',
            name='guests',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], null=True),
        ),
    ]
