# Generated by Django 3.0.1 on 2020-01-01 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0003_auto_20200101_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keytransfer',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='concierge.Person'),
        ),
    ]
