# Generated by Django 3.0.1 on 2020-01-01 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0004_auto_20200101_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='concierge.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='concierge.Person'),
        ),
    ]
