# Generated by Django 3.0.1 on 2020-01-01 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0006_auto_20200101_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='concierge.Room'),
        ),
        migrations.AlterField(
            model_name='keytransfer',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='concierge.Person'),
        ),
    ]
