# Generated by Django 3.0.1 on 2020-01-01 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0007_auto_20200101_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='concierge.Room'),
        ),
    ]
