# Generated by Django 3.0.1 on 2020-01-01 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0008_auto_20200101_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keytransfer',
            name='room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='concierge.Room'),
        ),
    ]
