# Generated by Django 3.0.1 on 2020-01-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0009_auto_20200101_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keytransfer',
            name='guests',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
