# Generated by Django 3.0.1 on 2020-01-15 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0011_auto_20200102_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keytransfer',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='keytransfer',
            name='room_id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Key',
        ),
        migrations.DeleteModel(
            name='KeyTransfer',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
