# Generated by Django 3.0.1 on 2020-01-26 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='KeyTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_out_data', models.DateTimeField(blank=True, null=True)),
                ('key_in_data', models.DateTimeField(blank=True, null=True)),
                ('guests', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('max_tenants', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, verbose_name='First name')),
                ('last_name', models.CharField(max_length=250, verbose_name='Last name')),
                ('date_of_birth', models.DateField(blank=True, db_index=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone num')),
                ('photo', models.ImageField(blank=True, help_text='Photo of the tenant', null=True, upload_to='tenant', verbose_name='Photo')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['first_name', 'last_name'], name='mycore_tena_first_n_59e684_idx'),
        ),
        migrations.AddField(
            model_name='room',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mycore.Person'),
        ),
        migrations.AddField(
            model_name='keytransfer',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mycore.Person'),
        ),
        migrations.AddField(
            model_name='keytransfer',
            name='room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mycore.Room'),
        ),
        migrations.AddField(
            model_name='key',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='mycore.Room'),
        ),
    ]
