# Generated by Django 3.0.1 on 2020-01-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
